export { ApiError, apiRequest } from './client'
export { useApi } from './useApi'
export type { ApiState } from './useApi'

export { fetchProject, fetchProjects } from './projects'
export { fetchVacancies, fetchVacancy } from './vacancies'
export { fetchDirections } from './directions'
export { fetchHallOfFame } from './hallOfFame'
export { fetchDefaultPortfolio } from './portfolio'
export { fetchDepartmentContacts } from './contacts'
export type { DepartmentContacts } from './contacts'
